language: node_js

dist: trusty

node_js:
  - 12

addons:
  apt:
    packages:
      - libnss3

before_install:
  - "sysctl kernel.unprivileged_userns_clone=1"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm run lint
  - npm run build

script:
  - npm run test-all

notifications:
  email:
    recipients:
      # Please don't spam me!
      - travisci-notifications@stanlemon.com
    on_success: always
    on_failure: always
